ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-OPU9PE3\Msyu];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

